### ISSUE TITLE
PHPHttpServer demo 安装后，请求报错 curl http://10.40.0.100:10003/Index/index

### ISSUE THREAD

**Issue by monkeycraps** [TarsPHP/TarsPHP#5]
```
PHP Fatal error:  Uncaught Exception: -99 in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/protocol/TARSProtocol.php:29
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Event.php(90): Tars\protocol\TARSProtocol->route(Object(Tars\core\Request), Object(Tars\core\Response))
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(379): Tars\core\Event->onRequest(Object(Tars\core\Request), Object(Tars\core\Response))
#2 {main}
  thrown in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/protocol/TARSProtocol.php on line 29
[2018-10-15 03:42:56 *9732.0]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Exception: -99 in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/protocol/TARSProtocol.php:29
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Event.php(90): Tars\protocol\TARSProtocol->route(Object(Tars\core\Request), Object(Tars\core\Response))
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server
```

**Comment by monkeycraps** [comment]
mac 上打包，在 centos 7 上执行

**Comment by monkeycraps** [comment]
看注释如下
```
        $paramInfos = $request->paramInfos;
        // 发生了注释异常,说明生成的注释有问题
        if (!isset($paramInfos[$sFuncName])) {
            throw new \Exception(Code::TARSSERVERUNKNOWNERR);
        }
        $paramInfo = $paramInfos[$sFuncName];

```

**Comment by meijing0114** [comment]
看起来像是没有使用http的模板，导致解析到了tars的协议去了。
<tars>
 <application>
...
    <client>
...
   </client>
   <server>
     ...
      protocolName=http
    </server>
 </application>
</tars>
